language: c
compiler: gcc

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6

script: 
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - gcc -v
  - export CC=/usr/bin/gcc-6
  - mkdir -p m4
  - autoreconf -ifv
  - ./configure
  - make check
