language: c
compiler: gcc

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

script: 
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
  - mkdir -p m4
  - autoreconf -ifv
  - ./configure
  - make check
