language: c
compiler: gcc

dist: trusty
sudo: require

matrix:
  include:
    # mininal version for __auto_type support
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
        - CC_IN_USE="/usr/bin/gcc-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
        - CC_IN_USE="/usr/bin/gcc-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - CC_IN_USE="/usr/bin/gcc-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - CC_IN_USE="/usr/bin/gcc-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - CC_IN_USE="/usr/bin/gcc-8"

    # x86-64 uthread context test for gcc-4.9
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
        - CC_IN_USE="/usr/bin/gcc-4.9"
        - ENABLE_X64_CNTX="1"

    # x86-64 uthread context test for gcc-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - CC_IN_USE="/usr/bin/gcc-8"
        - ENABLE_X64_CNTX="1"


before_install:
  - sudo unlink /usr/bin/gcc && sudo ln -s "${CC_IN_USE}" /usr/bin/gcc
  - if [ "${ENABLE_X64_CNTX}" -eq "1" ]; then [ `uname -m` = "x86_64" ] && export TEST_CMD="./configure --enable-arch-specified-impl && make check" || export TEST_CMD='echo "Test skipped for architecture `uname -m`"'; else export TEST_CMD="./configure && make check"; fi

script: 
  - gcc --version
  - mkdir -p m4
  - autoreconf -ifv
  - echo "build_arch=`uname -m`"
  - echo "test_command=${TEST_CMD}"
  - eval "${TEST_CMD}"

after_success:
  - bash <(curl -s https://codecov.io/bash)
