language: c
compiler: gcc

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  - CC_IN_USE="CC=gcc-4.9"

before_install:
  - eval "${CC_IN_USE}"

script: 
  - mkdir -p m4
  - autoreconf -ifv
  - ./configure
  - make check
