language: c
compiler: gcc

dist: trusty

matrix:
  include:
    - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
  env:
    - MATRIX_EVAL="CC=gcc-4.9"

before_install:
  - eval "${MATRIX_EVAL}"

script: 
  - mkdir -p m4
  - autoreconf -ifv
  - ./configure
  - make check
